class_name Boss extends Node3D

func _enter_tree() -> void:
	GlobalContext.Register(self)

func set_grid_size(size: Vector2i) -> void:
	position = Vector3(size.x + 0.5, 0.0, (size.y - 1) / 2.0)

func queue_patterns() -> void:
	Pattern.Row(1).Telegraph(4.125)
	Pattern.Row(2).Telegraph(4.75)
	Pattern.Row(3).Telegraph(5.625)
	Pattern.Row(4).Telegraph(6.75)
	Pattern.Advance(8.0)
	Pattern.Row(4).Telegraph(4.125)
	Pattern.Row(3).Telegraph(4.75)
	Pattern.Row(2).Telegraph(5.625)
	Pattern.Row(1).Telegraph(6.75)
	Pattern.Advance(8.0)
	Pattern.Row(1).Telegraph(4.125)
	Pattern.Row(2).Telegraph(4.75)
	Pattern.Row(3).Telegraph(5.625)
	Pattern.Row(4).Telegraph(6.75)
	Pattern.Advance(8.0)
	Pattern.Row(4).Telegraph(4.125)
	Pattern.Row(3).Telegraph(4.75)
	Pattern.Row(2).Telegraph(5.625)
	Pattern.Row(1).Telegraph(6.75)
	Pattern.Advance(8.0)
	Pattern.Column("a").Telegraph(4.125)
	Pattern.Column("b").Telegraph(4.75)
	Pattern.Column("c").Telegraph(5.625)
	Pattern.Column("d").Telegraph(6.75)
	Pattern.Advance(8.0)
	Pattern.Column("d").Telegraph(4.125)
	Pattern.Column("c").Telegraph(4.75)
	Pattern.Column("b").Telegraph(5.625)
	Pattern.Column("a").Telegraph(6.75)
	Pattern.Advance(8.0)
	Pattern.Column("a").Telegraph(4.125)
	Pattern.Column("b").Telegraph(4.75)
	Pattern.Column("c").Telegraph(5.625)
	Pattern.Column("d").Telegraph(6.75)
	Pattern.Advance(8.0)
	Pattern.Column("d").Telegraph(4.125)
	Pattern.Column("c").Telegraph(4.75)
	Pattern.Column("b").Telegraph(5.625)
	#Pattern.Column("a").Telegraph(6.75)
	
	Pattern.Advance(6.0)
	
	full_boombox_pattern()
	
	Pattern.Advance(6.0)
	
	Pattern.Single("a2").Telegraph(4.125)
	Pattern.Single("b2").Telegraph(4.75)
	Pattern.Single("c2").Telegraph(5.625)
	Pattern.Single("d2").Telegraph(6.75)
	Pattern.Advance(4.0)
	Pattern.Single("d3").Telegraph(4.125)
	Pattern.Single("c3").Telegraph(4.75)
	Pattern.Single("b3").Telegraph(5.625)
	Pattern.Single("a3").Telegraph(6.75)
	Pattern.Advance(4.0)
	Pattern.Single("a2").Telegraph(4.125)
	Pattern.Single("b2").Telegraph(4.75)
	Pattern.Single("c2").Telegraph(5.625)
	Pattern.Single("d2").Telegraph(6.75)
	Pattern.Advance(4.0)
	Pattern.Single("d3").Telegraph(4.125)
	Pattern.Single("c3").Telegraph(4.75)
	Pattern.Single("b3").Telegraph(5.625)
	Pattern.Single("a3").Telegraph(6.75)
	Pattern.Advance(4.0)
	Pattern.Single("a2").Telegraph(4.125)
	Pattern.Single("b2").Telegraph(4.75)
	Pattern.Single("c2").Telegraph(5.625)
	Pattern.Single("d2").Telegraph(6.75)
	Pattern.Advance(4.0)
	Pattern.Single("d3").Telegraph(4.125)
	Pattern.Single("c3").Telegraph(4.75)
	Pattern.Single("b3").Telegraph(5.625)
	Pattern.Single("a3").Telegraph(6.75)
	Pattern.Advance(4.0)
	
	Pattern.Single("d2").Telegraph(2.0).Delay(2.0)
	Pattern.Single("d3").Telegraph(2.0).Delay(2.0)
	Pattern.Single("b2").Telegraph(2.0).Delay(3.0)
	Pattern.Single("b3").Telegraph(2.0).Delay(3.0)
	Pattern.Advance(2.0)
	Pattern.Single("c2").Telegraph(2.0).Delay(2.0)
	Pattern.Single("c3").Telegraph(2.0).Delay(2.0)
	Pattern.Single("a2").Telegraph(2.0).Delay(3.0)
	Pattern.Single("a3").Telegraph(2.0).Delay(3.0)
	Pattern.Advance(2.0)
	Pattern.Single("d2").Telegraph(2.0).Delay(2.0)
	Pattern.Single("d3").Telegraph(2.0).Delay(2.0)
	Pattern.Single("b2").Telegraph(2.0).Delay(3.0)
	Pattern.Single("b3").Telegraph(2.0).Delay(3.0)
	Pattern.Advance(2.0)
	Pattern.Single("c2").Telegraph(2.0).Delay(2.0)
	Pattern.Single("c3").Telegraph(2.0).Delay(2.0)
	Pattern.Single("a2").Telegraph(2.0).Delay(3.0)
	Pattern.Single("a3").Telegraph(2.0).Delay(3.0)
	Pattern.Advance(2.0)
	
	Pattern.Single("d2").Telegraph(2.0).Delay(2.0)
	Pattern.Single("d3").Telegraph(2.0).Delay(2.0)
	Pattern.Single("b2").Telegraph(2.0).Delay(3.0)
	Pattern.Single("b3").Telegraph(2.0).Delay(3.0)
	Pattern.Advance(2.0)
	Pattern.Single("c2").Telegraph(2.0).Delay(2.0)
	Pattern.Single("c3").Telegraph(2.0).Delay(2.0)
	Pattern.Single("a2").Telegraph(2.0).Delay(3.0)
	Pattern.Single("a3").Telegraph(2.0).Delay(3.0)
	Pattern.Advance(2.0)
	Pattern.Single("d2").Telegraph(2.0).Delay(2.0)
	Pattern.Single("d3").Telegraph(2.0).Delay(2.0)
	Pattern.Single("b2").Telegraph(2.0).Delay(3.0)
	Pattern.Single("b3").Telegraph(2.0).Delay(3.0)
	Pattern.Advance(2.0)
	Pattern.Single("c2").Telegraph(2.0).Delay(2.0)
	Pattern.Single("c3").Telegraph(2.0).Delay(2.0)
	Pattern.Single("a2").Telegraph(2.0).Delay(3.0)
	Pattern.Single("a3").Telegraph(2.0).Delay(3.0)
	Pattern.Advance(2.0)
	Pattern.Single("d2").Telegraph(2.0).Delay(2.0)
	Pattern.Single("d3").Telegraph(2.0).Delay(2.0)
	Pattern.Single("b2").Telegraph(2.0).Delay(3.0)
	Pattern.Single("b3").Telegraph(2.0).Delay(3.0)
	Pattern.Advance(2.0)
	Pattern.Single("c2").Telegraph(2.0).Delay(2.0)
	Pattern.Single("c3").Telegraph(2.0).Delay(2.0)
	Pattern.Single("a2").Telegraph(2.0).Delay(3.0)
	Pattern.Single("a3").Telegraph(2.0).Delay(3.0)
	Pattern.Advance(2.0)
	Pattern.Single("d2").Telegraph(2.0).Delay(2.0)
	Pattern.Single("d3").Telegraph(2.0).Delay(2.0)
	Pattern.Single("b2").Telegraph(2.0).Delay(3.0)
	Pattern.Single("b3").Telegraph(2.0).Delay(3.0)
	Pattern.Advance(2.0)
	Pattern.Single("c2").Telegraph(2.0).Delay(2.0)
	Pattern.Single("c3").Telegraph(2.0).Delay(2.0)
	Pattern.Single("a2").Telegraph(2.0).Delay(3.0)
	Pattern.Single("a3").Telegraph(2.0).Delay(3.0)
	Pattern.Advance(2.0)
	Pattern.Single("d2").Telegraph(2.0).Delay(2.0)
	Pattern.Single("d3").Telegraph(2.0).Delay(2.0)
	Pattern.Single("b2").Telegraph(2.0).Delay(3.0)
	Pattern.Single("b3").Telegraph(2.0).Delay(3.0)
	Pattern.Advance(2.0)
	Pattern.Single("c2").Telegraph(2.0).Delay(2.0)
	Pattern.Single("c3").Telegraph(2.0).Delay(2.0)
	Pattern.Single("a2").Telegraph(2.0).Delay(3.0)
	Pattern.Single("a3").Telegraph(2.0).Delay(3.0)
	Pattern.Advance(2.0)
	
	Pattern.Column("a").Telegraph(2.0).Delay(2.125)
	Pattern.Column("d").Telegraph(2.0).Delay(2.75)
	Pattern.Row(1).Telegraph(2.0).Delay(3.625)
	Pattern.Row(4).Telegraph(2.0).Delay(4.75)
	
	# Beat 128

	
	#Pattern.Row(1).Telegraph(0.125)

	#Pattern.Row(1).Telegraph(4.25)
	#Pattern.Advance(8.0)
	#Pattern.Row(4).Telegraph(4.25)
	#Pattern.Advance(8.0)
	#Pattern.Row(1).Telegraph(4.25)
	#Pattern.Advance(8.0)
	#Pattern.Row(4).Telegraph(4.25)
	#Pattern.Advance(8.0)
	#Pattern.Column("a").Telegraph(4.25)
	#Pattern.Advance(8.0)
	#Pattern.Column("d").Telegraph(4.25)
	#Pattern.Advance(8.0)
	#Pattern.Column("b").Telegraph(4.25)
	#Pattern.Column("c").Telegraph(4.25)
	#Pattern.Advance(8.0)
	#Pattern.Row(2).Telegraph(4.25)
	#Pattern.Row(3).Telegraph(4.25)
	
func full_boombox_pattern() -> void:
	boombox_pattern_eight_beats(0)
	boombox_pattern_eight_beats(8)
	boombox_pattern_eight_beats(16)
	boombox_pattern_eight_beats(24)
	boombox_pattern_eight_beats(32)
	boombox_pattern_eight_beats(40)
	boombox_pattern_eight_beats(48)
	Pattern.Single("a1").Telegraph(2).Delay(56)
	Pattern.Single("a4").Telegraph(2).Delay(56)
	Pattern.Single("d1").Telegraph(2).Delay(56)
	Pattern.Single("d4").Telegraph(2).Delay(56)
	Pattern.Single("b1").Telegraph(2).Delay(57)
	Pattern.Single("c1").Telegraph(2).Delay(57)
	Pattern.Single("b4").Telegraph(2).Delay(57)
	Pattern.Single("c4").Telegraph(2).Delay(57)
	Pattern.Single("a1").Telegraph(2).Delay(58)
	Pattern.Single("a4").Telegraph(2).Delay(58)
	Pattern.Single("d1").Telegraph(2).Delay(58)
	Pattern.Single("d4").Telegraph(2).Delay(58)
	Pattern.Single("b1").Telegraph(2).Delay(59)
	Pattern.Single("c1").Telegraph(2).Delay(59)
	Pattern.Single("b4").Telegraph(2).Delay(59)
	Pattern.Single("c4").Telegraph(2).Delay(59)
	
	for i in range(8):
		boombox_pattern_eight_beats(64 + i * 8)

func boombox_pattern_eight_beats(delay: int) -> void:
	Pattern.Single("a1").Telegraph(2).Delay(0 + delay)
	Pattern.Single("a4").Telegraph(2).Delay(0 + delay)
	Pattern.Single("d1").Telegraph(2).Delay(0 + delay)
	Pattern.Single("d4").Telegraph(2).Delay(0 + delay)
	Pattern.Single("b1").Telegraph(2).Delay(1 + delay)
	Pattern.Single("c1").Telegraph(2).Delay(1 + delay)
	Pattern.Single("b4").Telegraph(2).Delay(1 + delay)
	Pattern.Single("c4").Telegraph(2).Delay(1 + delay)
	Pattern.Single("a1").Telegraph(2).Delay(2 + delay)
	Pattern.Single("a4").Telegraph(2).Delay(2 + delay)
	Pattern.Single("d1").Telegraph(2).Delay(2 + delay)
	Pattern.Single("d4").Telegraph(2).Delay(2 + delay)
	Pattern.Single("b1").Telegraph(2).Delay(3 + delay)
	Pattern.Single("c1").Telegraph(2).Delay(3 + delay)
	Pattern.Single("b4").Telegraph(2).Delay(3 + delay)
	Pattern.Single("c4").Telegraph(2).Delay(3 + delay)
	Pattern.Single("a1").Telegraph(2).Delay(4 + delay)
	Pattern.Single("a4").Telegraph(2).Delay(4 + delay)
	Pattern.Single("d1").Telegraph(2).Delay(4 + delay)
	Pattern.Single("d4").Telegraph(2).Delay(4 + delay)
	Pattern.Single("b1").Telegraph(2).Delay(5 + delay)
	Pattern.Single("c1").Telegraph(2).Delay(5 + delay)
	Pattern.Single("b4").Telegraph(2).Delay(5 + delay)
	Pattern.Single("c4").Telegraph(2).Delay(5 + delay)
	Pattern.Single("a1").Telegraph(2).Delay(6 + delay)
	Pattern.Single("a4").Telegraph(2).Delay(6 + delay)
	Pattern.Single("d1").Telegraph(2).Delay(6 + delay)
	Pattern.Single("d4").Telegraph(2).Delay(6 + delay)
	Pattern.Single("b1").Telegraph(2).Delay(7 + delay)
	Pattern.Single("c1").Telegraph(2).Delay(7 + delay)
	Pattern.Single("b4").Telegraph(2).Delay(7 + delay)
	Pattern.Single("c4").Telegraph(2).Delay(7 + delay)
